name: ci-golang-workflow
on: [push]

jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Run tests
        run: |
          cd GOAPP_ALUNO
          go test ./...

      - name: Run application
        run: |
          cd GOAPP_ALUNO
          go run math.go

