# Esse workflow roda testes e executa a aplicação Go
name: ci-golang-workflow

on:
  # Roda quando há push ou PR para a branch develop
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24 

      - name: Run tests
        run: |
          cd GOAPP_ALUNO
          go test ./...

      - name: Run application
        run: |
          cd GOAPP_ALUNO
          go run math.go
      
      - name: Set up QEMU
        uses: docker/setup-buildx-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: ./GOAPP_ALUNO
          file: ./GOAPP_ALUNO/Dockerfile
          push: true
          tags: bran00/continuousintegration:latest

